# Рабочая директория
root = "."
tmp_dir = "tmp"

[build]
  # Команда сборки (используем main.go в ./cmd)
  cmd = "go run ./cmd"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "bin", "vendor"]
  delay = 500               # задержка между пересборками (мс)
  stop_on_error = true
  send_interrupt = true
  log = "build.log"
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta